#!/usr/bin/env python3
"""Assemble FINDINGS.md from the latest analysis outputs.

Re-runnable: each invocation stitches the current output/*.md files
(which themselves are regenerated from the full capture) into one
report. Run ``make all`` first to refresh everything.
"""

from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "output"

NIGHT_ONE_SECTIONS = [
    ("data_quality.md", "Data quality"),
    ("analysis_seasonality.md", None),
    ("analysis_imbalance.md", None),
    ("analysis_leadlag.md", None),
    ("analysis_volclustering.md", None),
    ("analysis_epps.md", None),
    ("analysis_tape.md", None),
    ("analysis_anomalies.md", None),
    ("backtest.md", None),
]

NIGHT_TWO_SECTIONS = [
    ("venue_quality.md", None),
    ("replication_results.md", None),
    ("replication_h1.md", None),
    ("analysis_crossvenue.md", None),
]

PREAMBLE = """\
# FINDINGS

Generated by `make all` from the raw captures. Charts live in
`output/`; the section sources are the individual `output/*.md` reports.

**Two clearly separated datasets:**

- **Night one (2026-06-10, Binance.US):** ~5.5 h, top-20 book at ~1/s
  plus the full trade tape, BTC/ETH/SOL.
- **Night two (2026-06-10 → 06-11, Kraken + Coinbase):** 30 h dual-venue
  book capture (book-only — no trade tape), with a **pre-registered
  replication** of night one's headline finding (`REPLICATION.md`,
  frozen before any night-two statistic was computed).

**Standing caveats:** 1-second snapshots, retail-scale data, two
sessions. Nothing here is investment research; it is a methodology
exhibit, and the statistics are deliberately conservative (HAC errors,
Bonferroni corrections, deflated Sharpe, random nulls, pre-registration,
and stale-data exclusion documented where applied).
"""

NIGHT_ONE_HEADER = """\
# PART I — Night one: Binance.US (book + trade tape)
"""

NIGHT_TWO_HEADER = """\
# PART II — Night two: Kraken + Coinbase (dual-venue book capture,
# pre-registered replication, cross-venue price discovery)
"""


def render_sections(sections: list[tuple[str, str | None]]) -> list[str]:
    parts = []
    for fname, retitle in sections:
        path = OUT / fname
        if not path.exists():
            print(f"warning: {fname} missing — run `make all` first")
            continue
        text = path.read_text()
        if retitle:
            _, rest = text.split("\n", 1)
            text = f"# {retitle}\n{rest}"
        # demote headings one level and fix image paths relative to repo root
        text = text.replace("# ", "## ", 1)
        for img in ("![chart](", "![epps]("):
            text = text.replace(img, img[:-1] + "(output/")
        parts.append(text)
    return parts


def main() -> None:
    parts = [PREAMBLE, f"_Generated {datetime.now(UTC):%Y-%m-%d %H:%M} UTC._\n"]
    parts.append(NIGHT_ONE_HEADER)
    parts += render_sections(NIGHT_ONE_SECTIONS)
    parts.append(NIGHT_TWO_HEADER)
    parts += render_sections(NIGHT_TWO_SECTIONS)
    (ROOT / "FINDINGS.md").write_text("\n\n---\n\n".join(parts))
    print(f"wrote {ROOT / 'FINDINGS.md'}")


if __name__ == "__main__":
    main()
