#!/usr/bin/env python3
"""Assemble FINDINGS.md from the latest analysis outputs.

Re-runnable: each invocation stitches the current output/*.md files
(which themselves are regenerated from the full capture) into one
report. Run ``make all`` first to refresh everything.
"""

from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "output"

SECTIONS = [
    ("data_quality.md", "Data quality"),
    ("analysis_seasonality.md", None),
    ("analysis_imbalance.md", None),
    ("analysis_leadlag.md", None),
    ("analysis_volclustering.md", None),
    ("analysis_epps.md", None),
    ("backtest.md", None),
]

PREAMBLE = """\
# FINDINGS — one night of Binance.US microstructure

Everything below is generated by `make all` from the raw overnight
capture (top-20 order book snapshots at ~1/s plus the trade tape for
BTC, ETH and SOL). Charts live next to this file in `output/`; the
section sources are the individual `output/*.md` reports.

**Standing caveats, applying to every section:** one venue, one night,
1-second snapshots. Nothing here is investment research; it is a
methodology exhibit over a small dataset, and the statistics are
deliberately conservative (HAC errors, Bonferroni corrections, deflated
Sharpe, random-strategy nulls).
"""


def main() -> None:
    parts = [PREAMBLE, f"_Generated {datetime.now(UTC):%Y-%m-%d %H:%M} UTC._\n"]
    for fname, retitle in SECTIONS:
        path = OUT / fname
        if not path.exists():
            print(f"warning: {fname} missing — run `make all` first")
            continue
        text = path.read_text()
        if retitle:
            _, rest = text.split("\n", 1)
            text = f"# {retitle}\n{rest}"
        # demote headings one level and fix image paths relative to repo root
        text = text.replace("# ", "## ", 1).replace("![chart](", "![chart](output/")
        parts.append(text)
    (ROOT / "FINDINGS.md").write_text("\n\n---\n\n".join(parts))
    print(f"wrote {ROOT / 'FINDINGS.md'}")


if __name__ == "__main__":
    main()
